<a href="https://colab.research.google.com/github/Kai-White/COMP-SCI-5530-HW2/blob/main/Train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Kai-White/COMP-SCI-5530-HW2/refs/heads/main/Source/train.csv')

In [3]:
df.head(10)

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50
5,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50
6,8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,5.20
7,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,Diesel,Manual,Second,22.3 kmpl,1248 CC,74 bhp,5.0,NaN,1.95
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56 kmpl,1462 CC,103.25 bhp,5.0,10.65 Lakh,9.95
9,11,Honda City 1.5 V AT Sunroof,Kolkata,2012,60000,Petrol,Automatic,First,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.49

In [4]:
df.isna().mean()

Unnamed: 0           0.000000
Name                 0.000000
Location             0.000000
Year                 0.000000
Kilometers_Driven    0.000000
Fuel_Type            0.000000
Transmission         0.000000
Owner_Type           0.000000
Mileage              0.000342
Engine               0.006157
Power                0.006157
Seats                0.006499
New_Price            0.860612
Price                0.000000
dtype: float64

86% of New_Price entries are blank. It would not be smart to replace these values with mean, median, or mode because it is the target variable. If we want to be focused on New_Price, we don't want our data to be based on created values.

Once null New_Price entries are removed, there are no other variables missing except for a miniscule amount of missing mileage entries. We can afford to drop them.

In [5]:
df = df.dropna(subset=['New_Price'])
df = df.dropna(subset=['Mileage'])
df.isna().mean()

Unnamed: 0           0.0
Name                 0.0
Location             0.0
Year                 0.0
Kilometers_Driven    0.0
Fuel_Type            0.0
Transmission         0.0
Owner_Type           0.0
Mileage              0.0
Engine               0.0
Power                0.0
Seats                0.0
New_Price            0.0
Price                0.0
dtype: float64

In [6]:
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
5,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56 kmpl,1462 CC,103.25 bhp,5.0,10.65 Lakh,9.95
13,15,Mitsubishi Pajero Sport 4X4,Delhi,2014,110000,Diesel,Manual,First,13.5 kmpl,2477 CC,175.56 bhp,7.0,32.01 Lakh,15.00
18,20,BMW 3 Series 320d,Kochi,2014,32982,Diesel,Automatic,First,22.69 kmpl,1995 CC,190 bhp,5.0,47.87 Lakh,18.55

Removing units

In [7]:
df['Mileage']=df['Mileage'].astype(str)
df['Mileage'] = (
    df['Mileage']
    .str.replace(',', '', regex=False)
    .str.extract(r'(\d+\.?\d*)', expand=False)
)
df['Engine']=df['Engine'].astype(str)
df['Engine'] = (
    df['Engine']
    .str.replace(',', '', regex=False)
    .str.extract(r'(\d+\.?\d*)', expand=False)
)
df['New_Price']=df['New_Price'].astype(str)
df['New_Price'] = (
    df['New_Price']
    .str.replace(',', '', regex=False)
    .str.extract(r'(\d+\.?\d*)', expand=False)
)
df['Power']=df['Power'].astype(str)
df['Power'] = (
    df['Power']
    .str.replace(',', '', regex=False)
    .str.extract(r'(\d+\.?\d*)', expand=False)
)
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13,1199,88.7,5.0,8.61,4.50
5,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36,2755,171.5,8.0,21,17.50
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56,1462,103.25,5.0,10.65,9.95
13,15,Mitsubishi Pajero Sport 4X4,Delhi,2014,110000,Diesel,Manual,First,13.5,2477,175.56,7.0,32.01,15.00
18,20,BMW 3 Series 320d,Kochi,2014,32982,Diesel,Automatic,First,22.69,1995,190,5.0,47.87,18.55

In [8]:
one_hot = pd.get_dummies(df['Fuel_Type'].apply(pd.Series).stack()).groupby(level=0).sum()
df_one_hot = df.drop('Fuel_Type', axis=1).join(one_hot)
one_hot_transmission = pd.get_dummies(df_one_hot['Transmission'].apply(pd.Series).stack()).groupby(level=0).sum()
new_df = df_one_hot.drop('Transmission', axis=1).join(one_hot_transmission)
new_df

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Diesel,Petrol,Automatic,Manual
1,2,Honda Jazz V,Chennai,2011,46000,First,13,1199,88.7,5.0,8.61,4.50,0,1,0,1
5,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,First,11.36,2755,171.5,8.0,21,17.50,1,0,1,0
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,First,21.56,1462,103.25,5.0,10.65,9.95,0,1,0,1
13,15,Mitsubishi Pajero Sport 4X4,Delhi,2014,110000,First,13.5,2477,175.56,7.0,32.01,15.00,1,0,0,1
18,20,BMW 3 Series 320d,Kochi,2014,32982,First,22.69,1995,190,5.0,47.87,18.55,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5827,5999,Tata Bolt Revotron XT,Chennai,2016,10000,First,17.57,1193,88.7,5.0,7.77,4.00,0,1,0,1
5830,6002,Volkswagen Vento 1.6 Highline,Mumbai,2011,38000,First,16.09,1598,103.5,5.0,11.91,3.25,0,1,0,1
5833,6005,Maruti Vitara Brezza VDi,Pune,2016,37208,First,24.3,1248,88.5,5.0,9.93,7.43,1,0,0,1
5838,6010,Honda Brio 1.2 VX MT,Delhi,2013,33746,First,18.5,1198,86.8,5.0,6.63,3.20,0,1,0,1
5842,6014,Maruti Swift VDI,Delhi,2014,27365,First,28.4,1248,74,5.0,7.88,4.75,1,0,0,1

Adding car brand column

In [14]:
df["Brand"]= df["Name"].str.split().str.get(0)
df

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Brand
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13,1199,88.7,5.0,8.61,4.50,Honda
5,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36,2755,171.5,8.0,21,17.50,Toyota
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56,1462,103.25,5.0,10.65,9.95,Maruti
13,15,Mitsubishi Pajero Sport 4X4,Delhi,2014,110000,Diesel,Manual,First,13.5,2477,175.56,7.0,32.01,15.00,Mitsubishi
18,20,BMW 3 Series 320d,Kochi,2014,32982,Diesel,Automatic,First,22.69,1995,190,5.0,47.87,18.55,BMW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5827,5999,Tata Bolt Revotron XT,Chennai,2016,10000,Petrol,Manual,First,17.57,1193,88.7,5.0,7.77,4.00,Tata
5830,6002,Volkswagen Vento 1.6 Highline,Mumbai,2011,38000,Petrol,Manual,First,16.09,1598,103.5,5.0,11.91,3.25,Volkswagen
5833,6005,Maruti Vitara Brezza VDi,Pune,2016,37208,Diesel,Manual,First,24.3,1248,88.5,5.0,9.93,7.43,Maruti
5838,6010,Honda Brio 1.2 VX MT,Delhi,2013,33746,Petrol,Manual,First,18.5,1198,86.8,5.0,6.63,3.20,Honda
5842,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4,1248,74,5.0,7.88,4.75,Maruti

Using equivalent select, filter, rename, mutate, arrange, summarize with group by operations.

In [26]:
df["Name"].groupby(df["Brand"]).count()

Brand
Audi              24
BMW               57
Datsun             7
Fiat               1
Ford              25
Honda             68
Hyundai           96
Isuzu              1
Jaguar             4
Jeep              15
Land              10
Mahindra          25
Maruti           185
Mercedes-Benz     42
Mini              16
Mitsubishi         6
Nissan            15
Porsche            1
Renault           27
Skoda             19
Tata              43
Toyota            82
Volkswagen        42
Volvo              3
Name: Name, dtype: int64

In [27]:
df[df["Brand"] == "Maruti"]

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Brand
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56,1462,103.25,5.0,10.65,9.95,Maruti
34,36,Maruti Vitara Brezza ZDi Plus,Kochi,2018,50075,Diesel,Manual,First,24.3,1248,88.5,5.0,11.12,8.63,Maruti
106,111,Maruti Eeco 5 Seater AC,Coimbatore,2017,38053,Petrol,Manual,First,15.1,1196,73,5.0,5.13,3.91,Maruti
114,119,Maruti Vitara Brezza VDi,Mumbai,2016,55000,Diesel,Manual,First,24.3,1248,88.5,5.0,9.96,7.50,Maruti
126,133,Maruti Alto K10 VXI,Hyderabad,2014,88500,Petrol,Manual,First,24.07,998,67.1,5.0,4.53,2.60,Maruti
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5771,5940,Maruti Dzire LDI,Pune,2018,27000,Diesel,Manual,First,28.4,1248,73.75,5.0,7.91,5.90,Maruti
5777,5947,Maruti Ertiga VXI AT Petrol,Mumbai,2017,28000,Petrol,Automatic,First,18.69,1462,103,7.0,10.65,8.00,Maruti
5811,5981,Maruti Baleno Alpha,Mumbai,2017,6000,Petrol,Manual,First,21.4,1197,83.1,5.0,8.78,7.50,Maruti
5833,6005,Maruti Vitara Brezza VDi,Pune,2016,37208,Diesel,Manual,First,24.3,1248,88.5,5.0,9.93,7.43,Maruti
5842,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4,1248,74,5.0,7.88,4.75,Maruti

In [31]:
imperial_df=df.rename(columns={"Mileage": "MPG","Kilometers_Driven": "Miles_Driven"})
imperial_df["Miles_Driven"]=df["Kilometers_Driven"]/1.6
imperial_df

,Unnamed: 0,Name,Location,Year,Miles_Driven,Fuel_Type,Transmission,Owner_Type,MPG,Engine,Power,Seats,New_Price,Price,Brand
1,2,Honda Jazz V,Chennai,2011,28750.000,Petrol,Manual,First,13,1199,88.7,5.0,8.61,4.50,Honda
5,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,22500.000,Diesel,Automatic,First,11.36,2755,171.5,8.0,21,17.50,Toyota
8,10,Maruti Ciaz Zeta,Kochi,2018,16057.500,Petrol,Manual,First,21.56,1462,103.25,5.0,10.65,9.95,Maruti
13,15,Mitsubishi Pajero Sport 4X4,Delhi,2014,68750.000,Diesel,Manual,First,13.5,2477,175.56,7.0,32.01,15.00,Mitsubishi
18,20,BMW 3 Series 320d,Kochi,2014,20613.750,Diesel,Automatic,First,22.69,1995,190,5.0,47.87,18.55,BMW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5827,5999,Tata Bolt Revotron XT,Chennai,2016,6250.000,Petrol,Manual,First,17.57,1193,88.7,5.0,7.77,4.00,Tata
5830,6002,Volkswagen Vento 1.6 Highline,Mumbai,2011,23750.000,Petrol,Manual,First,16.09,1598,103.5,5.0,11.91,3.25,Volkswagen
5833,6005,Maruti Vitara Brezza VDi,Pune,2016,23255.000,Diesel,Manual,First,24.3,1248,88.5,5.0,9.93,7.43,Maruti
5838,6010,Honda Brio 1.2 VX MT,Delhi,2013,21091.250,Petrol,Manual,First,18.5,1198,86.8,5.0,6.63,3.20,Honda
5842,6014,Maruti Swift VDI,Delhi,2014,17103.125,Diesel,Manual,First,28.4,1248,74,5.0,7.88,4.75,Maruti

In [34]:
imperial_df.sort_values(by="MPG",ascending=False)

,Unnamed: 0,Name,Location,Year,Miles_Driven,Fuel_Type,Transmission,Owner_Type,MPG,Engine,Power,Seats,New_Price,Price,Brand
5842,6014,Maruti Swift VDI,Delhi,2014,17103.125,Diesel,Manual,First,28.4,1248,74,5.0,7.88,4.75,Maruti
1877,1934,Maruti Dzire ZDI Plus,Jaipur,2017,15000.000,Diesel,Manual,First,28.4,1248,73.75,5.0,10.48,8.20,Maruti
2946,3040,Maruti Swift VDI,Kochi,2015,33437.500,Diesel,Manual,First,28.4,1248,74,5.0,7.88,5.36,Maruti
2920,3012,Maruti Swift LDI,Hyderabad,2016,32500.000,Diesel,Manual,First,28.4,1248,74,5.0,7.27,5.95,Maruti
2361,2438,Maruti Dzire VDI,Hyderabad,2011,68750.000,Diesel,Manual,First,28.4,1248,73.75,5.0,9.14,4.00,Maruti
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3164,3266,Mercedes-Benz E-Class E400 Cabriolet,Kolkata,2015,4688.125,Petrol,Automatic,First,10.0,2996,333,4.0,87.57,48.00,Mercedes-Benz
929,962,Mercedes-Benz C-Class Progressive C 220d,Mumbai,2018,5426.250,Diesel,Automatic,First,0.0,1950,194,5.0,52.26,39.50,Mercedes-Benz
65,67,Mercedes-Benz C-Class Progressive C 220d,Coimbatore,2019,9605.625,Diesel,Automatic,First,0.0,1950,194,5.0,49.14,35.67,Mercedes-Benz
5712,5875,Mercedes-Benz C-Class Progressive C 220d,Ahmedabad,2019,2500.000,Diesel,Automatic,First,0.0,1950,194,5.0,49.14,35.00,Mercedes-Benz
524,544,Mercedes-Benz New C-Class Progressive C 200,Kochi,2019,8243.750,Petrol,Automatic,First,0.0,1950,181.43,5.0,49.49,38.99,Mercedes-Benz

In [42]:
imperial_df.groupby("Brand").agg({
    "Price": "median",
    "Miles_Driven": "median",
    "Year":"min"
})

                Price  Miles_Driven  Year
Brand
Audi           27.765    23695.0000  2013
BMW            22.240    29375.0000  2009
Datsun          3.310    16399.3750  2016
Fiat            2.500    53750.0000  2013
Ford            8.450    13625.0000  2007
Honda           7.950    18437.5000  2004
Hyundai         6.075    23803.7500  2001
Isuzu          20.000    21518.1250  2017
Jaguar         39.000     4062.5000  2017
Jeep           18.500    18085.6250  2017
Land           57.930    22958.4375  2014
Mahindra        6.250    40625.0000  2012
Maruti          5.650    22015.6250  2010
Mercedes-Benz  49.985    15312.5000  2011
Mini           28.725    12646.5625  2012
Mitsubishi     13.875    40312.5000  2013
Nissan          5.430    31875.0000  2011
Porsche         2.020     8936.2500  2019
Renault         4.450    16250.0000  2012
Skoda          11.920    21875.0000  2005
Tata            5.000    23943.7500  2014
Toyota         17.960    28500.0000  2009
Volkswagen      6.940    21111.8750  2011
Volvo          24.000    31875.0000  2014